---
title: De Jong & Penzer Notes
author: Benjamin Moran
date: '2017-11-24'
slug: de-jong-penzer-notes
draft: TRUE
categories:
  - Modelling
tags:
  - Working Notes
---

```{r}
data("Nile")
plot(Nile)
```

```{r}
var.sig <- 15099
var.eta <- 1469.2 
a.0 <- Nile[1]

x <- c(NA)
a <- c(NA)
a[1] <- a.0
x[1] <- a.0 + rnorm(1,0,sqrt(var.sig))
for(i in 2:length(Nile)){
  a[i] = a[i-1] + rnorm(1,0,sqrt(var.eta))
  x[i] = a[i] + rnorm(1,0,sqrt(var.sig))
}
a <- ts(a, start = 1871, end = 1970)
x <- ts(x, start = 1871, end = 1970)

plot(x, type = "l")
lines(a, col = "red")

# levelshocks <- x - a
# plot(levelshocks, type = "l")
```

```{r, eval = FALSE}
library(KFAS)
x <- ts(datasets::Nile, start = 1871, end = 1970)
plot(x)

intercept <- 0
model_int <- SSModel(Nile ~ SSMtrend(1, Q = 1469) + SSMcustom(Z = 0, T = 1, Q = 0, a1 = intercept, P1inf = 1), H = 15099)

set.seed(123)
# simulate new observations from the "fitted" model
model <- SSModel(Nile ~ SSMtrend(1, Q = 1469), H = 15099)
# signal conditional on the data i.e. samples from p(theta | y)
# unconditional simulation is not reasonable as the model is nonstationary

dist_sim <- simulateSSM(model, type = "disturbances", nsim = 1, filtered = FALSE)
dist_sim
signal_sim <- simulateSSM(model, type = "signals", nsim = 10)
# and add unconditional noise term i.e samples from p(epsilon)
epsilon_sim <- simulateSSM(model, type = "epsilon", nsim = 10,
  conditional = FALSE, filtered = TRUE)
observation_sim <- signal_sim + epsilon_sim

ts.plot(observation_sim[,1,], Nile, col = c(rep(2, 10), 1),
  lty = c(rep(2, 10), 1), lwd = c(rep(1, 10), 2))

# fully unconditional simulation:
observation_sim2 <- simulateSSM(model, type = "observations", nsim = 10,  conditional = FALSE)
ts.plot(observation_sim[,1,], observation_sim2[,1,], Nile,
col = c(rep(2:3, each = 10), 1), lty = c(rep(2, 20), 1),
lwd = c(rep(1, 20), 2))
```


```{r}
library(MARSS)
dat = t(as.matrix(Nile))
mod.nile.0 = list(Z=matrix(1), 
                  A=matrix(0),
                  R=matrix(15099),
                  B=matrix(1),
                  U=matrix(0),
                  Q=matrix(0),
                  x0=matrix("a"))
kem.0 = MARSS(dat, model=mod.nile.0)

mod.nile.1 = list(
Z=matrix(1), A=matrix(0), R=matrix("r"),
B=matrix(1), U=matrix("u"), Q=matrix(0),
x0=matrix("a") )
kem.1 = MARSS(dat, model=mod.nile.1)
mod.nile.2 = list(Z=matrix(1), 
                  A=matrix(0),
                  R=matrix(15099),
                  B=matrix(1),
                  U=matrix(0),
                  Q=matrix(1469),
                  x0=matrix(1120))
kem.2em = MARSS(dat, model=mod.nile.2, silent=FALSE)
kem.2 = MARSS(dat, model=mod.nile.2,inits=kem.2em$par, method="BFGS")
# kem.2 = MARSS(dat, model=mod.nile.2, method="EM")


resids.2a = residuals(kem.2)
```
```{r}
resids.2=residuals(kem.2)$std.residuals
plot((abs(resids.2[1,]))^2, type = "l", yaxp = c(0,10,4))
abline(h = c(2.5,5,7.5), lty = 2)

resids.2=residuals(kem.2)$state.residuals
plot(abs(c(resids.2))^2, type = "l")
abline(h = c(2.5,5,7.5), lty = 2)

# resids.2=residuals(kem.2)$residuals

# x = abs(residuals(kem.1)$std.residuals[1,]) + abs(residuals(kem.1)$model.residuals[1,])
# plot(x,type = "l")
# abline(h = c(1.96), lty = 2)

test <- MARSSkfss(kem.2)
```

