---
title: Summary of available time series
author: Benjamin Moran
date: '2017-11-14'
categories:
  - Flutracking
tags:
  - Flutracking
slug: available-time-series
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE)
library(tidyverse)
library(lubridate)
library(reshape2)
library(htmlTable)

df <- readRDS("~/R/HonoursBlog/data/fludata.RDS")
df <- df %>%
  mutate(Year = factor(year(as.Date(.$Week_end)))) %>%
  mutate(Unvaccinated = .$Responses-.$Vaccinated_Respondents)

df2 <- melt(df,id = c("Week_end","fileref","Year"))
```


A brief summary of all of the available datasets within the publically available Flutracking reports. The data itself will be accessible on another page. This is still just a test.

# Summary Data

```{r}
breaks <- match(unique(df$Year), df$Year)
labbreaks <- c()
for(i in 1:(length(breaks)-1)){
  j = length(breaks)
  labbreaks[i] = ((breaks[i+1]-breaks[i])/2) + breaks[i]
  labbreaks[j] = ((nrow(df)-breaks[j])/2) + breaks[j]
}
labelsbreak <- levels(df[breaks, "Year"])
cols <- scales::brewer_pal(palette = "Set1")(8)
nsurv <- c()
for(i in 1:(length(breaks)-1)){
  j = length(breaks)
  nsurv[i] = breaks[i+1]-breaks[i]
  nsurv[j] = nrow(df)-breaks[j]
}
firstsurv <- df[breaks, "Week_end"]
lastsurv <- c()
for(i in 1:(length(breaks)-1)){
  j = length(breaks)
  lastsurv[i] = df[(breaks[i]+nsurv[i]-1), 1]
  lastsurv[j] = df[nrow(df), "Week_end"]
}
lastsurv <- levels(droplevels(df[lastsurv,1]))

sumdat <- data.frame(Year = unique(df$Year),
                     Number = nsurv,
                     FirstSurvey = firstsurv,
                     LastSurvey = lastsurv)

# sumdat %>%  kable("html") %>%  kable_styling(bootstrap_options = c("striped", "hover"))
htmlTable(sumdat)
```


# Plots of Respondents

## Total Respondents 

```{r Total}
cols <- scales::brewer_pal(palette = "Set1")(8)
dfresp <- df2[df2$variable %in% c("Responses"),]
dfvline <- as.data.frame(rep(levels(droplevels(unique(dfresp$variable))),length(breaks))) %>%
  cbind(rep(breaks,each = 4))

colnames(dfvline) <- c("variable","breaks")
dfvline <- group_by(dfvline, variable)

ggplot(data = dfresp,
       aes(x = Week_end, y = value, colour = Year, group = variable)) + 
  geom_point() +
  geom_path() +
  scale_colour_brewer(palette = "Set1") + 
  geom_vline(data = dfvline, aes(xintercept = breaks, colour = "lightgrey"), linetype = 2) +
  theme_minimal() +
  scale_x_discrete(labels = labelsbreak, 
                   breaks = df$Week_end[labbreaks]) +
  theme(panel.grid.major.x = element_blank(),
        legend.position = "none",
        panel.grid.minor.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank()) +
  labs(
    title = "Total Responses to the Flutracking Survey",
    subtitle = "by Year and survey week",
    caption = "Data from flutracking.net"
  ) 

```

## Types of Responses

```{r}
cols <- scales::brewer_pal(palette = "Set1")(8)
dfresp <- df2[df2$variable %in% c("Self_Report", "Other_Report"),]
endpoints <- sumdat[,2] + breaks - 1
endpoints[length(endpoints)] <-  nrow(df)
endpoints <- c(breaks, endpoints)
dfrespvals <- dfresp[c(endpoints,(endpoints + nrow(dfresp)/2)),]
dfrespvals <- cbind(dfrespvals, rep(breaks,2))

dfvline <- as.data.frame(rep(levels(droplevels(unique(dfresp$variable))),2)) %>%
  cbind(breaks = rep(breaks,each = 2))

colnames(dfvline) <- c("variable","breaks")
dfvline <- group_by(dfvline, variable)

ggplot(data = dfresp,
       aes(x = Week_end, y = value, group = interaction(Year, variable))) + 
    geom_vline(data = dfvline, aes(xintercept = breaks),
             colour = "lightgrey",
             linetype = 2,
             show.legend = FALSE) +
  geom_path(aes(colour = variable)) +
  geom_point(data = dfrespvals,
             aes(x = Week_end,
                 y = value,
                 group = interaction(Year, variable),
                 colour = variable),
             show.legend = FALSE) + 
  scale_colour_discrete(name="Reponse Type",
                      breaks=c("Self_Report", "Other_Report"),
                         labels=c("Self Reported", "Other")) +

  theme_minimal() +
  scale_x_discrete(labels = labelsbreak, 
                   breaks = df$Week_end[labbreaks]) +
  theme(panel.grid.major.x = element_blank(),
        legend.position = "bottom",
        panel.grid.minor.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank()) +
  labs(
    title = "Total Responses to the Flutracking Survey",
    subtitle = "by Response Type",
    caption = "Data from flutracking.net"
  ) 

```


## Self Reporting 

```{r SelfReport}
cols <- scales::brewer_pal(palette = "Set1")(8)
dfresp <- df2[df2$variable %in% c("Responses","Self_Report", "Other_Report"),]
dfvline <- as.data.frame(rep(levels(droplevels(unique(dfresp$variable))),length(breaks))) %>%
  cbind(rep(breaks,each = 3)) %>%
  cbind(rep(cols, each = 3))

colnames(dfvline) <- c("variable","breaks","cols2")
dfvline <- group_by(dfvline, variable)

ggplot(data = dfresp,
       aes(x = Week_end, y = value, colour = Year, group = variable)) + 
  geom_point() +
  geom_path() +
  facet_grid(variable~., scales = "free") +
  scale_colour_brewer(palette = "Set1") + 
  geom_vline(data = dfvline, aes(xintercept = breaks, colour = "lightgrey"), linetype = 2) +
  theme_minimal() +
  scale_x_discrete(labels = labelsbreak, 
                   breaks = df$Week_end[labbreaks]) +
  theme(panel.grid.major.x = element_blank(),
        legend.position = "none",
        panel.grid.minor.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank()) +
  labs(
    title = "Total Responses to the Flutracking Survey",
    subtitle = "by Year and survey week",
    caption = "Data from flutracking.net"
  ) 
```

## Reporting for Others

```{r OtherReport}
ggplot(data = df,
       aes(x = Week_end, y = Other_Report, colour = Year, group = Year)) + 
  geom_point() +
  geom_path() +
  scale_colour_brewer(palette = "Set1") + 
  # theme_minimal() +
  scale_x_discrete(labels = labelsbreak, 
                   breaks = df$Week_end[labbreaks]) +
  theme(panel.grid.major.x = element_blank(),
        legend.position = "none",
        panel.grid.minor.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank()) +
  geom_vline(xintercept = breaks, colour = cols, linetype = 2) +
  labs(
    title = "Total Responses to the Flutracking Survey",
    subtitle = "by Year and survey week",
    caption = "Data from flutracking.net"
  )
```
